apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: pd-ssd
provisioner: pd.csi.storage.gke.io
parameters:
  type: ckn-gcp-sc
  replication-type: none
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer