# apiVersion: v1
# kind: Service
# metadata:
#   name: ck-postgres
# spec:
#   type: "{{ .Values.service.type }}"
#   ports:
#     - port: {{ .Values.service.port }}
#       targetPort: 5432
#       protocol: TCP
#   selector:
#     app: ck-postgres 


apiVersion: v1
kind: Service
metadata:
  name: ck-postgres
  namespace: codekarma
spec:
  clusterIP: None
  selector:
    app: ck-postgres
  ports:
    - name: postgresql
      port: {{ .Values.service.port }}
      targetPort: postgresql