apiVersion: v1
kind: StatefulSet
metadata:
  name: ck-postgres
spec:
  serviceName: ck-postgres
  replicas: 1
  selector:
    matchLabels:
      app: ck-postgres
  template:
    metadata:
      labels:
        app: ck-postgres
    spec:
      securityContext:
        runAsUser: 1001
        fsGroup: 1001
      {{- if and .Values.nodeAffinity .Values.nodeAffinity.enabled }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: cloud.google.com/machine-family
                operator: In
                values:
                - {{ .Values.nodeAffinity.nodeType }}
      {{- end }}
      tolerations:
        {{- if .Values.tolerations }}
        {{- toYaml .Values.tolerations | nindent 8 }}
        {{- end }}
      containers:
        - name: ck-postgres
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
              name: postgresql
          envFrom:
            - secretRef:
                name: ck-postgres-secret
          resources:
            {{- toYaml .Values.resources | nindent 8 }}
          volumeMounts:
            - name: postgres-data
              mountPath: /bitnami/postgresql/
            - name: init-scripts
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: init-scripts
          configMap:
            name: ck-postgres-init
  # VolumeClaimTemplate for StatefulSet - creates PVC per pod
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: 
          - ReadWriteOnce
        storageClassName: {{ .Values.persistence.storageClass  }}
        resources:
          requests:
            storage: {{ .Values.persistence.size| default "10Gi" }}