apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ck-postgres
spec:
  serviceName: ck-postgres
  replicas: 2
  selector:
    matchLabels:
      app: ck-postgres
  template:
    metadata:
      labels:
        app: ck-postgres
    spec:
      securityContext:
        runAsUser: 1001
        fsGroup: 1001

{{- if and .Values.nodeAffinity .Values.nodeAffinity.enabled }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: cloud.google.com/machine-family
                    operator: In
                    values:
                      - {{ .Values.nodeAffinity.nodeType }}
{{- end }}

{{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | nindent 8 }}
{{- end }}

{{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | nindent 8 }}
{{- end }}
      containers:
        - name: ck-postgres
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          ports:
            - containerPort: {{ .Values.service.port }}
              name: postgresql
          envFrom:
            - secretRef:
                name: ck-postgres-secret
          env:
            - name: POSTGRESQL_REPLICATION_MODE
              value: "slave"
            
            - name: POSTGRESQL_REPLICATION_USER
              value: "{{ .Values.postgresql.replica_user }}"

            - name: POSTGRESQL_MASTER_HOST
              value: "ck-postgres-0.ck-postgres"

            - name: POSTGRESQL_MASTER_PORT_NUMBER
              value: "5432"
          
          resources:
{{ toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: postgres-data
              mountPath: /bitnami/postgresql/
            - name: init-scripts
              mountPath: /docker-entrypoint-initdb.d

      volumes:
        - name: init-scripts
          configMap:
            name: ck-postgres-init

  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: {{ .Values.persistence.storageClass }}
        resources:
          requests:
            storage: {{ .Values.persistence.size | default "10Gi" }}
