# AWS-specific values for storage-classes chart
# This will enable the EKS (gp3) StorageClass and disable GKE pd-ssd
storageclasses:
  classes:
    - name: auto-ebs-sc
      enabled: true
      isDefault: true
      provisioner: ebs.csi.eks.amazonaws.com
      volumeBindingMode: WaitForFirstConsumer
      parameters:
        type: gp3
        encrypted: "true"
