apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: ck-postgres
  namespace: codekarma
spec:
  teamId: flipkart

  numberOfInstances: 3

  postgresql:
    version: "15"

  volume:
    size: 10Gi
    storageClass: ckn-gcp-sc

  users:
    cknexus:
      - superuser
      - createdb

  databases:
    ckservicedb: cknexus