# apiVersion: apiextensions.k8s.io/v1
# kind: CustomResourceDefinition
# metadata:
#   name: servicemonitors.monitoring.coreos.com
#   labels:
#     app.kubernetes.io/name: prometheus-operator
# spec:
#   group: monitoring.coreos.com
#   names:
#     kind: ServiceMonitor
#     plural: servicemonitors
#     singular: servicemonitor
#     listKind: ServiceMonitorList
#     shortNames:
#       - sm
#   scope: Namespaced
#   versions:
#     - name: v1
#       served: true
#       storage: true
#       schema:
#         openAPIV3Schema:
#           type: object
#           # permissive: let the API accept any fields (avoid strict nested validation)
#           x-kubernetes-preserve-unknown-fields: true
#       subresources:
#         status: {}
