# Required values
name: "ck-ingress-alb"
namespace: "codekarma"
certificates:
  - "arn:aws:acm:ap-south-1:484907483585:certificate/d2f2ab1d-fad9-4714-9f3b-6360c28eb24f"
  - "arn:aws:acm:ap-south-1:484907483585:certificate/ffb4e97c-7cd4-4ec9-9688-d157a77de499"

# Optional value
loadBalancerName: ""  # Optional: if not set, AWS will generate automatically
groupName: "ck-ingress-alb-prod"

# Backend service configuration
backend:
  serviceName: "ck-ingress-nginx"
  servicePort: 80
