# Required values
name: "ck-ingress-alb"
namespace: "codekarma"
certificates:
  - "arn:aws:acm:us-east-2:484907483585:certificate/1de88822-f1c7-4290-80db-2e0a2282f189"
  - "arn:aws:acm:us-east-2:484907483585:certificate/20a7283a-6019-4c5b-a314-4b6cc3bc886c"

loadBalancerName: ""  # Optional: if not set, AWS will generate automatically
groupName: "ck-ingress-alb-dev"

# Backend service configuration
backend:
  serviceName: "ck-ingress-nginx"
  servicePort: 80
